accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'signup/', views.signup, name='signup'),
    url(r'', views.login, name='login'),
    url(r'logout/', views.logout, name='logout'),
    url(r'/(?P<username>[\w.@+-]+)/choose/', views.choose, name='choose'),
]

blog/urls.py
from . import views

from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = "blog"

urlpatterns = [
    url(r'(?P<username>[\w.@+-]+)/', views.homepage, name='home'),
    url(r'(?P<username>[\w.@+-]+)/search/', views.search, name='search'),
    url(r'(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/ssearch/', views.ssearch, name='ssearch'),
    url(r'(?P<username>[\w.@+-]+)/mysearch/', views.mysearch, name='mysearch'),
    url(r'(?P<username>[\w.@+-]+)/settings/', views.settings, name='settings'),
    url(r'(?P<username>[\w.@+-]+)/preferences/', views.preferences, name='preferences'),
    url(r'(?P<username>[\w.@+-]+)/updatepreferences/', views.updatepreferences, name='updatepreferences'),
    url(r'(?P<username>[\w.@+-]+)/bookmarksearch/', views.bookmarksearch, name='bookmarksearch'),
    url(r'(?P<username>[\w.@+-]+)/(?P<username2>[\w.@+-]+)/userinfo/', views.userinfo, name='userinfo'),
    url(r'(?P<username>[\w.@+-]+)/myques/', views.myques, name='myques'),
    url(r'(?P<username>[\w.@+-]+)/myans/', views.myans, name='myans'),
    url(r'(?P<username>[\w.@+-]+)/question/add/', views.QuestionCreate, name='ques_add'),
    url(r'(?P<username>[\w.@+-]+)/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/answer/add/', views.AnswerCreate, name='ans_add'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/question/vote/', views.vote, name='vote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/question/ans/', views.ans, name='ans'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/question/sortans/', views.sortans, name='sortans'),
    url(r'(?P<username>[\w.@+-]+)/sortques/', views.sortques, name='sortques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/deleteques/(?P<pk2>[0-9]+)/', views.deleteques, name='deleteques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/deleteques/(?P<search>[\w.@+-]+)/search', views.sdeleteques, name='sdeleteques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/qs_deleteques/', views.qs_deleteques, name='qs_deleteques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/ansdelete/(?P<pk2>[0-9]+)/(?P<pk3>[0-9]+)', views.ansdelete, name='ansdelete'),
    url(r'(?P<username>[\w.@+-]+)/notification/', views.notification, name='notification'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<pk2>[0-9]+)/bookmark/', views.bookmark, name='bookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/sbookmark/', views.sbookmark, name='sbookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/qs_bookmark/', views.qs_bookmark, name='qs_bookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nbookmark/', views.nbookmark, name='nbookmark'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<pk2>[0-9]+)/removebookmark/', views.removebookmark, name='removebookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/sremovebookmark/', views.sremovebookmark,name='sremovebookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/qs_removebookmark/', views.qs_removebookmark,name='qs_removebookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/bs_removebookmark/', views.bs_removebookmark,name='bs_removebookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nremovebookmark/', views.nremovebookmark, name='nremovebookmark'),

    url(r'(?P<username>[\w.@+-]+)/mybookmark/', views.mybookmark, name='mybookmark'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/quesvote/(?P<pk2>[0-9]+)/', views.quesvote, name='quesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/squesvote/(?P<search>[\w.@+-]+)/', views.squesvote, name='squesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/bs_quesvote/(?P<search>[\w.@+-]+)/', views.bs_quesvote, name='bs_quesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/qs_quesvote/(?P<search>[\w.@+-]+)/', views.qs_quesvote, name='qs_quesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nquesvote/', views.nquesvote, name='nquesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nansvote/', views.nansvote, name='nansvote'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/quesdownvote/(?P<pk2>[0-9]+)/', views.quesdownvote, name='quesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/squesdownvote/(?P<search>[\w.@+-]+)/', views.squesdownvote,name='squesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/bs_quesdownvote/(?P<search>[\w.@+-]+)/', views.bs_quesdownvote,name='bs_quesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/qs_quesdownvote/(?P<search>[\w.@+-]+)/', views.qs_quesdownvote,name='qs_quesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/quesdownvote/', views.nquesdownvote,name='nquesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nansdownvote/', views.nansdownvote, name='nansdownvote'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/ansvote/(?P<pk2>[0-9]+)/', views.ansvote, name='ansvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/ansdownvote/(?P<pk2>[0-9]+)/', views.ansdownvote, name='ansdownvote'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/allvote/', views.allvote, name='allvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/allansvote/', views.allansvote, name='allansvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nques/', views.nques, name='nques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/ndelete/', views.ndelete, name='ndelete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campus_quora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView

urlpatterns = [

    # admin-page
    url('admin/', admin.site.urls),

    # for sign-up
    url(r'', include('accounts.urls', namespace = 'accounts')),

    # for blogs
    url(r'blogs/', include('blog.urls', namespace = 'blog')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
from django.db.models.signals import post_save
from django.dispatch import receiver

TAGS = (
    (0,"Department"),
    (1,"Clubs"),
    (2,"placements"),
    (3,"fests"),
    (4,"hostel"),
    (5,"general")
)

TAGS = (
    (0,"Department"),
    (1,"Clubs"),
    (2,"placements"),
    (3,"fests"),
    (4,"hostel"),
    (5,"general")
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tags = MultiSelectField(choices=TAGS, default=0)
    visit = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         UserProfile.objects.create(user=instance)
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.userprofile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class ProfileForm(forms.ModelForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = UserProfile
        fields = ('tags',)

class UesrForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField(max_length=30, required=False)
    class Meta:
        model = User
        fields = ('username', 'password' )

accounts/views.py
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import *
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from blog.models import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# class SignUp(generic.CreateView):
#     form_class = UserCreationForm
#     success_url = reverse_lazy('login')
#     template_name = 'signup.html'


def choose(request, username):
    user = User.objects.get(username=username)
    user_ = UserProfile.objects.get(user=user)

    user_.visit = 1
    temp = []
    if request.POST.get('0'):
        print(request.POST.get('0'))
        temp.append('0')
        print(0)
    if request.POST.get('1'):
        print(request.POST.get('1'))
        temp.append('1')
        print(1)
    if request.POST.get('2'):
        print(request.POST.get('2'))
        temp.append('2')
        print(2)
    if request.POST.get('3'):
        print(request.POST.get('3'))
        temp.append('3')
        print(3)
    if request.POST.get('4'):
        print(request.POST.get('4'))
        temp.append('4')
        print(4)
    if request.POST.get('5'):
        print(request.POST.get('5'))
        temp.append('5')
        print(5)
    user_.tags = temp
    user_.save()
    return redirect('blog:home', user.username)



def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            user_ = UserProfile.objects.get(user=user)
            # return render(request, 'accounts/choose.html', {'username': username})
            if user_.visit == 0:
                return render(request, 'accounts/choose.html', {'username': username})
            else :
                return redirect('blog:home', username)

        else:
            form = UesrForm()
            return render(request, 'accounts/login.html', {'form': form, 'error': 'wrong credentials'})
    else:
        form = UesrForm()
        return render(request, 'accounts/login.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        form = SignUpForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if User.objects.filter(username=username).exists():
            form = SignUpForm()
            return render(request, 'accounts/signup.html', {'form': form, 'profile_form': profile_form, 'error':'Username already exist'})
        if password1 != password2:
            form = SignUpForm()
            return render(request, 'accounts/signup.html', {'form': form, 'profile_form': profile_form, 'error':'password not matches'})
        if User.objects.filter(email=email).exists():
            form = SignUpForm()
            return render(request, 'accounts/signup.html', {'form': form, 'profile_form': profile_form, 'error':'email already exist'})


        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            profile = profile_form.save(commit = False)
            profile.user = user
            profile.save()


            # send_mail(subject, message, from_email,to_list, fail_silently=True)
            subject = 'Thank you'
            message = 'hello'
            from_email = settings.EMAIL_HOST_USER
            to_list = [ settings.EMAIL_HOST_USER]
            send_mail(subject, message, from_email, to_list, fail_silently=True)


            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user1 = auth.authenticate(username=username, password=raw_password)
            auth.login(request, user1)
            return redirect('accounts:login')
        else:
            return render(request, 'accounts/signup.html', {'form': form, 'profile_form': profile_form,  'error':'Weak Password'})
    else:
        form = SignUpForm()
        profile_form = ProfileForm()
        return render(request, 'accounts/signup.html', {'form': form, 'profile_form': profile_form})


    # if request.method == 'POST':
    #     username = request.POST['username']
    #     password1 = request.POST['password1']
    #     password2 = request.POST['password2']
    #     email = request.POST['email']
    #     if User.objects.filter(username=username).exists():
    #         form = SignUpForm()
    #         return render(request, 'accounts/signup.html', {'form': form, 'error':'Username already exist'})
    #     if password1 != password2:
    #         form = SignUpForm()
    #         return render(request, 'accounts/signup.html', {'form': form, 'error':'password not matches'})
    #     if User.objects.filter(email=email).exists():
    #         form = SignUpForm()
    #         return render(request, 'accounts/signup.html', {'form': form, 'error':'email already exist'})
    #
    #     form = SignUpForm(request.POST, instance=request.user)
    #     profile_form = ProfileForm(request.POST, instance=request.user.userprofile)
    #     if form.is_valid() and profile_form.is_valid():
    #         form.save()
    #         profile.save()
    #
    #
    #         # send_mail(subject, message, from_email,to_list, fail_silently=True)
    #         subject = 'Thank you'
    #         message = 'hello'
    #         from_email = settings.EMAIL_HOST_USER
    #         to_list = [ settings.EMAIL_HOST_USER]
    #         send_mail(subject, message, from_email, to_list, fail_silently=True)
    #
    #
    #         username = form.cleaned_data.get('username')
    #         raw_password = form.cleaned_data.get('password1')
    #         user1 = auth.authenticate(username=username, password=raw_password)
    #         auth.login(request, user1)
    #         return redirect('accounts:login')
    # else:
    #     form = SignUpForm(instance=request.user)
    #     profile_form = ProfileForm(instance=request.user.userprofile)
    #     return render(request, 'accounts/signup.html', {'form': form, 'profile_form': profile_form})

def logout(request):
    auth.logout(request)
    return redirect('accounts:login')

accounts/templates/accounts/choose.html
{% load static %}

<head>
  <title>CSS Gallery</title>
  <link href="https://fonts.googleapis.com/css?family=Raleway:600,900" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


<style>

body{
	margin:0;
	color:#6a6f8c;
	font:600 16px/18px 'Open Sans',sans-serif;
	background-color : #000033;
}

ul {
  list-style-type: none;
}

li {
  display: inline-block;
}

input[type="checkbox"][id^="cb"] {
  display: none;
}

label {
  border: 1px solid #fff;
  padding: 10px;
  display: block;
  position: relative;
  margin: 10px;
  cursor: pointer;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

label::before {
  background-color: white;
  color: white;
  content: " ";
  display: block;
  border-radius: 50%;
  border: 1px solid grey;
  position: absolute;
  top: -5px;
  left: -5px;
  width: 25px;
  height: 25px;
  text-align: center;
  line-height: 28px;
  transition-duration: 0.4s;
  transform: scale(0);
}



label img {
  height: 100px;
  width: 100px;
  transition-duration: 0.2s;
  transform-origin: 50% 50%;
}

:checked+label {
  border-color: #ddd;
}

:checked+label::before {
  content: "✓";
  background-color: grey;
  transform: scale(1);
}

:checked+label img {
  transform: scale(0.9);
  box-shadow: 0 0 5px #333;
  z-index: -1;
}


<!--&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;-->
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: Raleway;
  background-color: #202125;
}

.heading {
    text-align: center;
    font-size: 2.0em;
    letter-spacing: 1px;
    padding: 40px;
    color: white;
}

.gallery-image {
  padding: 20px;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

.gallery-image img {
  height: 250px;
  width: 350px;
  transform: scale(1.0);
  transition: transform 0.4s ease;
}

.img-box {
  box-sizing: content-box;
  margin: 10px;
  height: 250px;
  width: 350px;
  overflow: hidden;
  display: inline-block;
  color: white;
  position: relative;
  background-color: white;
}

.caption {
  position: absolute;
  bottom: 5px;
  left: 20px;
  opacity: 0.0;
  transition: transform 0.3s ease, opacity 0.3s ease;
}

.transparent-box {
  height: 250px;
  width: 350px;
  background-color:rgba(0, 0, 0, 0);
  position: absolute;
  top: 0;
  left: 0;
  transition: background-color 0.3s ease;
}

.img-box:hover img {
  transform: scale(1.1);
}

.img-box:hover .transparent-box {
  background-color:rgba(0, 0, 0, 0.5);
}

.img-box:hover .caption {
  transform: translateY(-20px);
  opacity: 1.0;
}

.img-box:hover {
  cursor: pointer;
}

.caption > p:nth-child(2) {
  font-size: 0.8em;
}

.opacity-low {
  opacity: 0.5;
}

</style>

</head>


<br><br>





<body>


  <h3 style="color:yellow;font-size: 48px; text-align:center">Choose your preferences - {{username}}</h3>

<form action="{% url 'accounts:choose' username %}" method="post">
  {% csrf_token %}
  <div class="gallery-image">

   <ul>
    <li><input type="checkbox" id="cb1" name="0" checked />
      <label for="cb1">
        <div class="img-box">
          <img src="{% static "accounts/0.jpg" %}" alt="" />
          <div class="transparent-box">
            <div class="caption">
              <p>Department</p>
            </div>
          </div>
        </div>
        </label>
    </li>


     <li><input type="checkbox" id="cb2" name="1"  />
      <label for="cb2">
    <div class="img-box">
      <img src="{% static "accounts/1.jpg" %}" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Clubs</p>
        </div>
      </div>
    </div>
        </label>
    </li>

        <li><input type="checkbox" id="cb3" name="2" />
      <label for="cb3">
    <div class="img-box">
      <img src="{% static "accounts/2.jpg" %}" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Placement</p>
        </div>
      </div>
    </div>
       </label>
    </li>


      <li><input type="checkbox" id="cb4" name="3" />
      <label for="cb4">
    <div class="img-box">
      <img src="{% static "accounts/3.jpg" %}" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Clubs</p>
        </div>
      </div>
    </div>
     </label>
    </li>

<li><input type="checkbox" id="cb5" name="4" />
      <label for="cb5">
    <div class="img-box">
      <img src="{% static "accounts/4.jpg" %}" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Hostel</p>
        </div>
      </div>
    </div>
      </label>
    </li>

     <li><input type="checkbox" id="cb6" name="5" />
       <label for="cb6">
    <div class="img-box">
      <img src="{% static "accounts/5.jpg" %}" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>General</p>
        </div>
      </div>
    </div>
     </label>
    </li>
   </ul>

    <div class="group">
      <input type="submit" class="btn btn-outline-danger" value="Submit">
    </div>

  </div>
  </form>
</body>







<script>

$(function(){
  var centerShelfs,
      $body = $('body'),
      $topShelf = $('.shelf.top'),
      $middleShelf = $('.shelf.middle'),
      $bottomShelf = $('.shelf.bottom');

  centerShelfs = function(){
    var topShelfPosition = $body.height()/2;

    $topShelf.css('top', topShelfPosition);
    $middleShelf.css('top', topShelfPosition + 200);
    $bottomShelf.css('top', topShelfPosition + 400);
  };

  moveToShelf = function(e){
    e.preventDefault();
    $body.attr('class', '');
    $body.addClass(e.target.id);
  };

  // bind events
  $(window).on('resize', centerShelfs);
  $('.nav a').on('click', moveToShelf);

  // move to start position
  centerShelfs();

  window.setTimeout(function(){
    $body.addClass('view-middle-shelf');
  }, 500);
});






</script>

accounts/templates/accounts/temp_choose.html
{% load static %}

<head>
  <title>CSS Gallery</title>
  <link href="https://fonts.googleapis.com/css?family=Raleway:600,900" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


<style>

body{
	margin:0;
	color:#6a6f8c;
	font:600 16px/18px 'Open Sans',sans-serif;
	background-color : #000033;
}

ul {
  list-style-type: none;
}

li {
  display: inline-block;
}

input[type="checkbox"][id^="cb"] {
  display: none;
}

label {
  border: 1px solid #fff;
  padding: 10px;
  display: block;
  position: relative;
  margin: 10px;
  cursor: pointer;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

label::before {
  background-color: white;
  color: white;
  content: " ";
  display: block;
  border-radius: 50%;
  border: 1px solid grey;
  position: absolute;
  top: -5px;
  left: -5px;
  width: 25px;
  height: 25px;
  text-align: center;
  line-height: 28px;
  transition-duration: 0.4s;
  transform: scale(0);
}



label img {
  height: 100px;
  width: 100px;
  transition-duration: 0.2s;
  transform-origin: 50% 50%;
}

:checked+label {
  border-color: #ddd;
}

:checked+label::before {
  content: "✓";
  background-color: grey;
  transform: scale(1);
}

:checked+label img {
  transform: scale(0.9);
  box-shadow: 0 0 5px #333;
  z-index: -1;
}
</style>
</head>



<h3 style="color:yellow;font-size: 48px; text-align:center">Choose your preferences - {{username}}</h3>

<form action="{% url 'accounts:choose' username %}" method="post">
  {% csrf_token %}
  <ul>
    <li><input type="checkbox" id="cb1" name="0" checked />
      <label for="cb1"><img src="{% static "accounts/0.jpg" %}" /></label>
    </li>
    <li><input type="checkbox" id="cb2" name="1"  />
      <label for="cb2"><img src="{% static "accounts/1.jpg" %}" /></label>
    </li>
    <li><input type="checkbox" id="cb3" name="2" />
      <label for="cb3"><img src="{% static "accounts/2.jpg" %}" /></label>
    </li>
    <li><input type="checkbox" id="cb4" name="3" />
      <label for="cb4"><img src="{% static "accounts/3.jpg" %}" /></label>
    </li>
    <li><input type="checkbox" id="cb5" name="4" />
      <label for="cb5"><img src="{% static "accounts/4.jpg" %}" /></label>
    </li>
    <li><input type="checkbox" id="cb6" name="5" />
      <label for="cb6"><img src="{% static "accounts/5.jpg" %}" /></label>
    </li>
  </ul>
  <div class="group">
      <input type="submit" class="button" value="Submit">
  </div>


</form>