accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'signup/', views.signup, name='signup'),
    url(r'', views.login, name='login'),
    url(r'logout/', views.logout, name='logout'),
    url(r'/(?P<username>[\w.@+-]+)/choose/', views.choose, name='choose'),
]

blog/urls.py
from . import views

from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = "blog"

urlpatterns = [
    url(r'(?P<username>[\w.@+-]+)/', views.homepage, name='home'),
    url(r'(?P<username>[\w.@+-]+)/search/', views.search, name='search'),
    url(r'(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/ssearch/', views.ssearch, name='ssearch'),
    url(r'(?P<username>[\w.@+-]+)/mysearch/', views.mysearch, name='mysearch'),
    url(r'(?P<username>[\w.@+-]+)/settings/', views.settings, name='settings'),
    url(r'(?P<username>[\w.@+-]+)/preferences/', views.preferences, name='preferences'),
    url(r'(?P<username>[\w.@+-]+)/updatepreferences/', views.updatepreferences, name='updatepreferences'),
    url(r'(?P<username>[\w.@+-]+)/bookmarksearch/', views.bookmarksearch, name='bookmarksearch'),
    url(r'(?P<username>[\w.@+-]+)/(?P<username2>[\w.@+-]+)/userinfo/', views.userinfo, name='userinfo'),
    url(r'(?P<username>[\w.@+-]+)/myques/', views.myques, name='myques'),
    url(r'(?P<username>[\w.@+-]+)/myans/', views.myans, name='myans'),
    url(r'(?P<username>[\w.@+-]+)/question/add/', views.QuestionCreate, name='ques_add'),
    url(r'(?P<username>[\w.@+-]+)/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/answer/add/', views.AnswerCreate, name='ans_add'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/question/vote/', views.vote, name='vote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/question/ans/', views.ans, name='ans'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/question/sortans/', views.sortans, name='sortans'),
    url(r'(?P<username>[\w.@+-]+)/sortques/', views.sortques, name='sortques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/deleteques/(?P<pk2>[0-9]+)/', views.deleteques, name='deleteques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/deleteques/(?P<search>[\w.@+-]+)/search', views.sdeleteques, name='sdeleteques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/qs_deleteques/', views.qs_deleteques, name='qs_deleteques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/ansdelete/(?P<pk2>[0-9]+)/(?P<pk3>[0-9]+)', views.ansdelete, name='ansdelete'),
    url(r'(?P<username>[\w.@+-]+)/notification/', views.notification, name='notification'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<pk2>[0-9]+)/bookmark/', views.bookmark, name='bookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/sbookmark/', views.sbookmark, name='sbookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/qs_bookmark/', views.qs_bookmark, name='qs_bookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nbookmark/', views.nbookmark, name='nbookmark'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<pk2>[0-9]+)/removebookmark/', views.removebookmark, name='removebookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/sremovebookmark/', views.sremovebookmark,name='sremovebookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/qs_removebookmark/', views.qs_removebookmark,name='qs_removebookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/(?P<search>[\w.@+-]+)/bs_removebookmark/', views.bs_removebookmark,name='bs_removebookmark'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nremovebookmark/', views.nremovebookmark, name='nremovebookmark'),

    url(r'(?P<username>[\w.@+-]+)/mybookmark/', views.mybookmark, name='mybookmark'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/quesvote/(?P<pk2>[0-9]+)/', views.quesvote, name='quesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/squesvote/(?P<search>[\w.@+-]+)/', views.squesvote, name='squesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/bs_quesvote/(?P<search>[\w.@+-]+)/', views.bs_quesvote, name='bs_quesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/qs_quesvote/(?P<search>[\w.@+-]+)/', views.qs_quesvote, name='qs_quesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nquesvote/', views.nquesvote, name='nquesvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nansvote/', views.nansvote, name='nansvote'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/quesdownvote/(?P<pk2>[0-9]+)/', views.quesdownvote, name='quesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/squesdownvote/(?P<search>[\w.@+-]+)/', views.squesdownvote,name='squesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/bs_quesdownvote/(?P<search>[\w.@+-]+)/', views.bs_quesdownvote,name='bs_quesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/qs_quesdownvote/(?P<search>[\w.@+-]+)/', views.qs_quesdownvote,name='qs_quesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/quesdownvote/', views.nquesdownvote,name='nquesdownvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nansdownvote/', views.nansdownvote, name='nansdownvote'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/ansvote/(?P<pk2>[0-9]+)/', views.ansvote, name='ansvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/ansdownvote/(?P<pk2>[0-9]+)/', views.ansdownvote, name='ansdownvote'),

    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/allvote/', views.allvote, name='allvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/allansvote/', views.allansvote, name='allansvote'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/nques/', views.nques, name='nques'),
    url(r'(?P<pk>[0-9]+)/(?P<username>[\w.@+-]+)/ndelete/', views.ndelete, name='ndelete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campus_quora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView

urlpatterns = [

    # admin-page
    url('admin/', admin.site.urls),

    # for sign-up
    url(r'', include('accounts.urls', namespace = 'accounts')),

    # for blogs
    url(r'blogs/', include('blog.urls', namespace = 'blog')),

]

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('tags', 'question', 'title')

class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = ['answer']

blog/views.py
from django.contrib import auth
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib import messages
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import *
from .forms import QuestionForm,AnswerForm
from accounts.models import UserProfile
from .models import *
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

m = {0: 'Department', 1: 'Clubs', 2: 'placements', 3: 'fests', 4: 'hostel', 5: 'general'}
m1 = {'Department': 0, 'Clubs': 1, 'placements': 2, 'fests': 3, 'hostel': 4, 'general': 5}


@login_required
def homepage(request, username):
    questions = Question.objects.all()
    user = User.objects.get(username=username)
    user_ = UserProfile.objects.get(user=user)
    print(type(user_.tags))
    print(user_.tags)
    v = []
    b = []
    size = []
    for ques in questions:
        size.append(len(ques.answer_set.all()))
        a = 1
        for votes in user.quesvotes_set.all():
            if votes.Question.id == ques.id:
                v.append(0)
                a = 0
                break
        if a:
            v.append(1)

    for ques in questions:
        a = 1
        for bm in user.bookmark_set.all():
            if bm.Question.id == ques.id:
                b.append(0)
                a = 0
                break
        if a:
            b.append(1)

    return render(request, 'blog/home.html', {'user': user, 'questions': questions,'data': zip(questions, v, b,size)})


@login_required
def sortques(request, username):
    if request.method == 'POST':
        search_tag = request.POST.get("search", False)  # for avoiding multidictionary key error
        print(search_tag)
        if search_tag == "Preferences":

            user = User.objects.get(username=username)
            user_ = UserProfile.objects.get(user=user)
            tags1 = user_.tags
            tags = list(tags1)
            questions = Question.objects.filter(tags__in = tags)
            print('questions')
            print(questions)
            print('questions')
            print(type(tags[0]))
            print('falak')
            print(tags)
            v = []
            b = []
            size = []
            for ques in questions:
                size.append(len(ques.answer_set.all()))
                a = 1
                for votes in user.quesvotes_set.all():
                    if votes.Question.id == ques.id:
                        v.append(0)
                        a = 0
                        break
                if a:
                    v.append(1)

            for ques in questions:
                a = 1
                for bm in user.bookmark_set.all():
                    if bm.Question.id == ques.id:
                        b.append(0)
                        a = 0
                        break
                if a:
                    b.append(1)
            return render(request, 'blog/home.html',{'user': user, 'questions': questions, 'data': zip(questions, v, b, size)})


        else:
            return redirect('blog:home', username)

    else:
        return redirect('blog:home', username)

@login_required
def search(request, username):
    user = User.objects.get(username=username)
    if request.method == 'POST':
        # s = request.POST['search']
        # print(s)
        search_tag = request.POST.get("search", False) # for avoiding multidictionary key error

        if search_tag:
            print(search_tag)
            match_ques = Question.objects.filter(Q(tags__icontains=m1[search_tag]))
            v = []
            b = []
            size = []
            for ques in match_ques:
                size.append(len(ques.answer_set.all()))
                a = 1
                for votes in user.quesvotes_set.all():
                    if votes.Question.id == ques.id:
                        v.append(0)
                        a = 0
                        break
                if a:
                    v.append(1)

            for ques in match_ques:
                a = 1
                for bm in user.bookmark_set.all():
                    if bm.Question.id == ques.id:
                        b.append(0)
                        a = 0
                        break
                if a:
                    b.append(1)
            if match_ques:
                return render(request,'blog/search.html',{'user':user,'match_ques':match_ques, 'data': zip(match_ques, v, b, size), "search":search_tag})
            else:
                 return render(request,'blog/search.html',{'user':user,'error_message':'no questions :(', "search":search_tag})
        else:
            print(search_tag)
            return redirect('blog:home',username)

    else:
        return redirect('blog:home', username)

@login_required
def ssearch(request, username, search):
    print("search-------")
    print(type(search))
    print("search--------")
    print("search")
    if len(search) == 1:
        search1 = int(search)
        search = search1
        print(type(search))
        search = m[search]
    user = User.objects.get(username=username)
    match_ques = Question.objects.filter(Q(tags__icontains=m1[search]))
    v = []
    b = []
    size = []
    for ques in match_ques:
        size.append(len(ques.answer_set.all()))
        a = 1
        for votes in user.quesvotes_set.all():
            if votes.Question.id == ques.id:
                v.append(0)
                a = 0
                break
        if a:
            v.append(1)

    for ques in match_ques:
        a = 1
        for bm in user.bookmark_set.all():
            if bm.Question.id == ques.id:
                b.append(0)
                a = 0
                break
        if a:
            b.append(1)
    return render(request, 'blog/search.html', {'user': user, 'match_ques': match_ques, 'data': zip(match_ques, v, b,size), "search": search})

@login_required
def ans(request, pk, username):
    pk = int(pk)
    question = Question.objects.get(pk = pk)
    user = User.objects.get(username=username)
    qv = 1
    for votes in user.quesvotes_set.all():
        if votes.Question.id == question.id:
            qv = 0
            break
    size = len(question.answer_set.all())
    qb = 1
    for bm in user.bookmark_set.all():
        if bm.Question.id == question.id:
            qb = 0
            break

    v = []
    answer = []
    for ans in question.answer_set.all():
        a = 1
        answer.append(ans)
        for votes in user.ansvotes_set.all():
            if votes.Answer.id == ans.id:
                v.append(0)
                a = 0
                break
        if a:
            v.append(1)
    print(answer)
    return render(request,'blog/ans.html', {'question':question, 'user':user, 'size':size ,'qv':qv, 'qb':qb,  'data': zip(answer, v)})

@login_required
def sortans(request, pk, username):
    question = Question.objects.get(pk=pk)
    user = User.objects.get(username=username)
    qv = 1
    for votes in user.quesvotes_set.all():
        if votes.Question.id == question.id:
            qv = 0
            break

    qb = 1
    for bm in user.bookmark_set.all():
        if bm.Question.id == question.id:
            qb = 0
            break
    if request.method == 'POST':
        size = len(question.answer_set.all())
        search_tag = request.POST.get("search", False)  # for avoiding multidictionary key error
        print(search_tag)
        if search_tag == "Votes":
            answer = question.answer_set.all().order_by('-votes', '-created_on') # - for decreasing order
            v = []
            for ans in answer:
                a = 1
                for votes in user.ansvotes_set.all():
                    if votes.Answer.id == ans.id:
                        v.append(0)
                        a = 0
                        break
                if a:
                    v.append(1)
            return render(request, 'blog/anssort.html', {'question':question, 'user': user, 'size':size , 'qv':qv, 'qb':qb, 'data': zip(answer, v)})
        else:
            return redirect('blog:ans', pk, username)

    else:
        return redirect('blog:ans', pk, username)

@login_required
def mysearch(request, username):
    print(username)
    print(6)
    user = User.objects.get(username=username)
    if request.method == 'POST':
        # s = request.POST['search']
        # print(s)
        search_tag = request.POST.get("search", False) # for avoiding multidictionary key error

        if search_tag:
            print(search_tag)
            match_ques = Question.objects.filter(Q(tags__icontains=m1[search_tag]), User = user)
            v = []
            b = []
            for ques in match_ques:
                a = 1
                for votes in user.quesvotes_set.all():
                    if votes.Question.id == ques.id:
                        v.append(0)
                        a = 0
                        break
                if a:
                    v.append(1)

            for ques in match_ques:
                a = 1
                for bm in user.bookmark_set.all():
                    if bm.Question.id == ques.id:
                        b.append(0)
                        a = 0
                        break
                if a:
                    b.append(1)
            # print(search_tag)
            if match_ques:
                return render(request,'blog/mysearch.html',{'user': user,'match_ques': match_ques,'data': zip(match_ques, v, b), 'search':search_tag})
            else:
                 return render(request,'blog/mysearch.html',{'user':user,'error_message':'no question','search':search_tag})
        else:
            print(search_tag)
            return redirect('blog:home',username)

    else:
        return redirect('blog:home', username)

@login_required

blog/templates/blog/nques.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}Notificatin Detail{% endblock %}

{% block body %}
{% if user.is_authenticated %}

<body>

<h1 style="color:yellow;font-size: 48px; text-align:center">Notification Question</h1>


<div class="container ctr">

<div class="movie_card card " id="bright">
  <div class="info_section">
    <div class="movie_header">
      {% if notification.Question.tags == 0 %}  <img class="locandina" img src="{% static "blog/0.jpg" %}" alt="My image"  />
      {% elif notification.Question.tags == 1 %}<img class="locandina" img src="{% static "blog/1.jpg" %}" alt="My image"  />
      {% elif notification.Question.tags == 2 %}<img class="locandina" img src="{% static "blog/2.jpg" %}" alt="My image"  />
      {% elif notification.Question.tags == 3 %}<img class="locandina" img src="{% static "blog/3.jpg" %}" alt="My image"  />
      {% elif notification.Question.tags == 4 %}<img class="locandina" img src="{% static "blog/4.jpg" %}" alt="My image"  />
      {% elif notification.Question.tags == 5 %}<img class="locandina" img src="{% static "blog/5.jpg" %}" alt="My image"  />
      {% endif %}
      <h1>{{notification.Question.title }}</h1>
        <h4>by.- <a href="{% url 'blog:userinfo' user.username notification.User.username %}">{{notification.Question.User}}</a></h4>
      <span class="minutes">
          {% if not b %}
            <a href = "{% url 'blog:nremovebookmark' notification.id  user.username %}"><img src="{% static "blog/bookmark.png" %}" alt="My image" width="25" height="25" ></a><br>
       {% else %}
            <a href = "{% url 'blog:nbookmark' notification.id  user.username %}"> <img src="{% static "blog/Unbookmark.png" %}" alt="My image" width="25" height="25" ></a><br>
      {% endif %}

      </span>

        {% if user.username == notification.Question.User.username %}
            &nbsp&nbsp
            <button type="button" class="btn btn-default btn-sm">
                <a href="{% url 'blog:deleteques' notification.Question.id user.username 4 %}" style="text-decoration: none;"><i class="fas fa-trash"></i></a>
            </button>
        {% endif %}
        &nbsp&nbsp


 <a href="{% url 'blog:ssearch' user.username notification.Question.tags %}">
                <button type="button" class="btn btn-warning">
                        <font color="blue">

                        <i class="far fa-share-square">
                          {% if notification.Question.tags == 0 %}Department
                          {% elif notification.Question.tags == 1 %}Clubs
                          {% elif notification.Question.tags == 2 %}placements
                          {% elif notification.Question.tags == 3 %}fests
                          {% elif notification.Question.tags == 4 %}hostel
                          {% elif notification.Question.tags == 5 %}general{% endif %}<br>
                        </i>
                        </font>
                </button>
            </a>


    </div>
    <div class="movie_desc">

      <p class="text bdy" word-wrap="break-word" >
        {{notification.Question.question}}
         </p></div>

    <div class="movie_social">
      <ul>

          <li><i class="material-icons">
              {% if not qv %}
            <a href = "{% url 'blog:nquesdownvote' notification.id user.username %}"> <img src="{% static "blog/Like.ico" %}" alt="My image" width="25" height="25" ></a>
        {% else %}
             <a href = "{% url 'blog:nquesvote' notification.id  user.username %}"> <img src="{% static "blog/Unlike.png" %}" alt="My image" width="25" height="25" ></a>
        {% endif %}


          <a href="{% url 'blog:allvote' notification.Question.id user.username %}"  >{{notification.Question.votes}}</a>&nbsp&nbsp</i></li>
        <li><i class="material-icons">
            <button type="button" class="btn btn-default btn-sm">
                        <i class="far fa-comment-alt"><a href="{% url 'blog:ans' notification.Question.id user.username %}" style="text-decoration: none;">&nbsp{{size}}&nbsp&nbspComment</a></i>
            </button>

        </i></li>

        <li><i class="material-icons"><div class="float-right">
            <footer class="blockquote-footer float-right" ><cite title="Source Title">{{notification.Question.created_on}}</cite></footer>
        </div></i></li>
      </ul>
    </div>
  </div>
  <div class="blur_back bright_back"></div>
</div>

</div>




<div class="container ctr" >

    <div class="card">

        <div class="bdy " style="background-color: #347EAF">
<!--                <h5 class="card-title" style="align-content: flex-start" >Question test</h5>-->
            <p class="card-text" ><font color = "#000000"><h3>&nbsp&nbspAns. {{notification.Answer.answer}}</h3></font>
                    </p>
            <div style="background-color: #CCE5FF">
            <b><hr  NOSHADE="noshade"></b>
                {% if not av %}
                    <a href = "{% url 'blog:nansdownvote' notification.id user.username %}"><img src="{% static "blog/Like.ico" %}" alt="My image" width="25" height="25" ></a>
                {% else %}
                    <a href = "{% url 'blog:nansvote' notification.id  user.username %}"><img src="{% static "blog/Unlike.png" %}" alt="My image" width="25" height="25" ></a>
                {% endif %}
                <a href="{% url 'blog:allansvote' notification.Answer.id user.username %}"  >{{notification.Answer.votes}} </a>


            <footer class=" float-right" >By <cite title="Source Title">
            <a href="{% url 'blog:userinfo' user.username notification.Answer.User.username %}"><font color = "#000000">{{notification.Answer.User}}</font></a>&nbsp&nbsp</cite></footer><br>

            <footer class="blockquote-footer float-right" ><cite title="Source Title" style="color:white">{{notification.Answer.created_on}}</cite></footer>

            </div>

    </div>
    </div>
</div>
<br>

<div class="card text-center">
<a href="{% url 'blog:ans' notification.Question.id user.username %}" class="btn btn-primary">See all ans</a>
</div>









{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'accounts:login' %}">login</a>
{% endif %}

</body>
{% endblock body %}

blog/templates/blog/temp_myans.html
{% extends "blog/base.html" %}
{% load static %}


{% block body %}
{% if user.is_authenticated %}

<body>

<h1 style="color:yellow;font-size: 48px; text-align:center">My Answers</h1>

{% for ques,qv,b,data2 in data %}
<div class="container ctr">
    <div class="card">
    <div class="card-header text-center">
        {{ques.title }}
    </div>
    <div class="card-body">
        <div class="topright">
        {% if not b %}
            <a href = "{% url 'blog:removebookmark' ques.id user.username 3 %}"><img src="{% static "blog/bookmark.png" %}" alt="My image" width="25" height="25" ></a><br>
       {% else %}
            <a href = "{% url 'blog:bookmark' ques.id user.username 3 %}"> <img src="{% static "blog/Unbookmark.png" %}" alt="My image" width="25" height="25" ></a><br>
      {% endif %}
        </div>


        <div class="bdy">
<!--                <h5 class="card-title" style="align-content: flex-start" >Question test</h5>-->
                <p class="card-text">Q. {{ques.question}}
                    </p>
            <b><hr></b>
                {% if not qv %}
                        <a href = "{% url 'blog:quesdownvote' ques.id user.username 3 %}"><img src="{% static "blog/Like.ico" %}" alt="My image" width="25" height="25" ></a>
                 {% else %}
                        <a href = "{% url 'blog:quesvote' ques.id user.username 3 %}"><img src="{% static "blog/Unlike.png" %}" alt="My image" width="25" height="25" ></a>
                 {% endif %}
                <a href="{% url 'blog:allvote' ques.id user.username %}"  >{{ques.votes}}</a>&nbsp&nbsp

                <button type="button" class="btn btn-default btn-sm">
                        <a href="{% url 'blog:ans' ques.id user.username %}" style="text-decoration: none;"><i class="far fa-comment-alt">&nbspComment</a></i>
                </button>
                <button type="button" class="btn btn-default btn-sm">
                        <i class="far fa-share-square">
                          {% if ques.tags == 0 %}Department
                          {% elif ques.tags == 1 %}Clubs
                          {% elif ques.tags == 2 %}placements
                          {% elif ques.tags == 3 %}fests
                          {% elif ques.tags == 4 %}hostel
                          {% elif ques.tags == 5 %}general{% endif %}<br>
                        </i>
                </button>
            <div class="float-right">
            <footer class="blockquote-footer" >By <cite title="Source Title">{{ques.User}}</cite></footer></div><br>
            <footer class="blockquote-footer float-right" ><cite title="Source Title">{{ques.created_on}}</cite></footer>
        </div>

    </div>
    </div>
    {% for ans,x in data2 %}

            <div class="card text-center">

            <div class="card-body border border-black">

            <p class="card-text">Ans. {{ans.answer}} </p>
            <p class="card-text"><h6>By -- {{ans.User}}</h6></p>
            <!--      <p>{{ans.id}}</p>-->


            {% if not x %}
            <a href = "{% url 'blog:ansdownvote' ans.id user.username 1 %}"><img src="{% static "blog/Like.ico" %}" alt="My image" width="25" height="25" ></a>
            {% else %}
            <a href = "{% url 'blog:ansvote' ans.id user.username 1 %}"><img src="{% static "blog/Unlike.png" %}" alt="My image" width="25" height="25" ></a>
            {% endif %}
            &nbsp&nbsp<a href="{% url 'blog:allansvote' ans.id user.username %}"  >{{ans.votes}} </a><br>
            </div>
            <div class="card-footer text-muted border-black">
            {{ans.created_on}}
            </div>
                <button type="button" class="btn btn-default btn-sm">
                    <a href="{% url 'blog:ansdelete' ans.id user.username %}" style="text-decoration: none;"><i class="fas fa-trash"></i></a>
                </button>
            <br><br>
            </div>


    {% endfor %}
</div>
    <form method="post" action="{% url 'blog:ans_add' user.username ques.pk 1  %}">
    {% csrf_token %}
    <input type="text" name="answer" size="500">
    <button>ans</button>
    </form>

<br><br>
<h1><hr></h1>
{% endfor %}



{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'accounts:login' %}">login</a>
{% endif %}

</body>
{% endblock body %}